# Generated by Django 5.1.5 on 2025-01-23 13:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0002_products_productimage'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='settings',
            name='image',
        ),
        migrations.RemoveField(
            model_name='settings',
            name='video',
        ),
        migrations.AlterField(
            model_name='products',
            name='created_at',
            field=models.DateTimeField(auto_now_add=True, null=True, verbose_name='Дата создания'),
        ),
        migrations.AlterField(
            model_name='settings',
            name='title',
            field=models.CharField(max_length=255, verbose_name='Заголовок'),
        ),
    ]
