# Generated by Django 5.1.5 on 2025-02-05 08:16

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0005_category'),
    ]

    operations = [
        migrations.CreateModel(
            name='Сharacteristic',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=255, verbose_name='Характеристика')),
                ('сharacteristic', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='main.products', verbose_name='Характеристики')),
            ],
            options={
                'verbose_name': 'Характеристика',
                'verbose_name_plural': 'Характеристики',
            },
        ),
        migrations.DeleteModel(
            name='Category',
        ),
    ]
